[ERROR] 2018-11-13 10:53:39,650 | /home/a2k/nextErp/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-11-13 10:53:39.544923-127.0.0.1-3fa
